package br.com.ws.customerservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-02-04T22:22:06.191-02:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://customerservice.example.com/service", name = "CustomerService")
@XmlSeeAlso({ObjectFactory.class, br.com.ws.customerservice.model.ObjectFactory.class})
public interface CustomerService {

    @WebResult(name = "return", targetNamespace = "http://customerservice.example.com/service")
    @RequestWrapper(localName = "getCustomerById", targetNamespace = "http://customerservice.example.com/service", className = "br.com.ws.customerservice.GetCustomerById")
    @WebMethod
    @ResponseWrapper(localName = "getCustomerByIdResponse", targetNamespace = "http://customerservice.example.com/service", className = "br.com.ws.customerservice.GetCustomerByIdResponse")
    public br.com.ws.customerservice.model.Customer getCustomerById(
        @WebParam(name = "customerId", targetNamespace = "http://customerservice.example.com/service")
        java.lang.Integer customerId
    ) throws NoSuchCustomerException;

    @WebResult(name = "customerId", targetNamespace = "http://customerservice.example.com/service")
    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://customerservice.example.com/service", className = "br.com.ws.customerservice.UpdateCustomer")
    @WebMethod
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://customerservice.example.com/service", className = "br.com.ws.customerservice.UpdateCustomerResponse")
    public java.lang.Integer updateCustomer(
        @WebParam(name = "customer", targetNamespace = "http://customerservice.example.com/service")
        br.com.ws.customerservice.model.Customer customer
    );

    @Oneway
    @RequestWrapper(localName = "deleteCustomerById", targetNamespace = "http://customerservice.example.com/service", className = "br.com.ws.customerservice.DeleteCustomerById")
    @WebMethod
    public void deleteCustomerById(
        @WebParam(name = "customerId", targetNamespace = "http://customerservice.example.com/service")
        java.lang.Integer customerId
    ) throws NoSuchCustomerException;
}
