
package br.com.ws.customerservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-02-04T22:22:06.155-02:00
 * Generated source version: 2.4.1
 */

@WebFault(name = "NoSuchCustomer", targetNamespace = "http://customerservice.example.com/service")
public class NoSuchCustomerException extends Exception {
    
    private br.com.ws.customerservice.NoSuchCustomer noSuchCustomer;

    public NoSuchCustomerException() {
        super();
    }
    
    public NoSuchCustomerException(String message) {
        super(message);
    }
    
    public NoSuchCustomerException(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchCustomerException(String message, br.com.ws.customerservice.NoSuchCustomer noSuchCustomer) {
        super(message);
        this.noSuchCustomer = noSuchCustomer;
    }

    public NoSuchCustomerException(String message, br.com.ws.customerservice.NoSuchCustomer noSuchCustomer, Throwable cause) {
        super(message, cause);
        this.noSuchCustomer = noSuchCustomer;
    }

    public br.com.ws.customerservice.NoSuchCustomer getFaultInfo() {
        return this.noSuchCustomer;
    }
}
